module.exports = {
    LISTALLPRODUCTS : 1,
    GETPRODUCT : 2,
    EDITPRODUCT : 3,
    ADDPRODUCT : 4,
    DELETEPRODUCT : 5,
    SEARCHPRODUCT : 6,
    ADDPRODUCTSTOCK : 7,
    DELETEPRODUCTSTOCK : 8,
    LISTALLBRANDS : 9,
    GETAUTHTOKEN : 10
};